services:
  nginx-app:
    image: ${ECR_REGISTRY}/${ECR_REPO_NGINX}:${IMAGE_TAG}
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"  # 외부에서는 80만 보임
    volumes:
      - /home/ec2-user/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/ec2-user/nginx/html:/usr/share/nginx/html
      - /home/ec2-user/nginx/logs:/var/log/nginx
    networks:
      app-network:
        aliases:
          - nginx-svc

  fastapi-app:
    image: ${ECR_REGISTRY}/${ECR_REPO_FASTAPI}:${IMAGE_TAG}
    container_name: fastapi-container
    restart: always
    # 리버스 프록시를 통하므로 8000포트를 외부에 노출(ports)할 필요 없음
    # 컨테이너 간 통신을 위해 내부적으로는 8000 오픈
    expose:
      - "8000"
    networks:
      app-network:
        aliases:
          - fastapi-svc

networks:
  app-network:
    driver: bridge